export const refs = {
  articleListView: document.getElementById('articleListView'),
  articleView: document.getElementById('articleView'),
  articleTitle: document.getElementById('articleTitle'),
  updatedAt: document.getElementById('updatedAt'),
  blocksContainer: document.getElementById('blocksContainer'),
  articleList: document.getElementById('articleList'),
  createArticleBtn: document.getElementById('createArticleBtn'),
  backToList: document.getElementById('backToList'),
  toast: document.getElementById('toast'),
  searchInput: document.getElementById('searchInput'),
  searchResults: document.getElementById('searchResults'),
  searchPanel: document.querySelector('.search-panel'),
  articleTitleInput: document.getElementById('articleTitleInput'),
  editTitleBtn: document.getElementById('editTitleBtn'),
  hintToggleBtn: document.getElementById('hintToggleBtn'),
  hintPopover: document.getElementById('hintPopover'),
  sidebar: document.getElementById('sidebar'),
  sidebarToggle: document.getElementById('sidebarToggle'),
  sidebarArticleList: document.getElementById('sidebarArticleList'),
  sidebarNewArticleBtn: document.getElementById('sidebarNewArticleBtn'),
  articleFilterInput: document.getElementById('articleFilterInput'),
  lastChangeValue: document.getElementById('lastChangeValue'),
  articleMenuBtn: document.getElementById('articleMenuBtn'),
  articleMenu: document.getElementById('articleMenu'),
  deleteArticleBtn: document.getElementById('deleteArticleBtn'),
};
